apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 3001       # The port to access the service
      targetPort: 3001 # The port the container is listening on
  type: NodePort      # Expose this service outside the cluster
